### ISSUE TITLE
Add css reset

### ISSUE THREAD

**Issue by ALMaclaine** [ALMaclaine/tag-manager#10]
Add this reset to global.css

```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box.
}
```
